# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e77d3657d64e646f1bb96010408497f75f175769b4c3352ec75ab19adfe8cdeb520fd3d2db197f50faff883fc36ab3308618b463bfd78cceb078a71d2660bd8

test:
  secret_key_base: d0fc8adc47906f4ad2f03695f70483c8a3bb4a55043f4abaae84dc85761d9367f45dd7e528d03cfcc26294152fb0d41e59448332eccf369874ee108f01fc387b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
