# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efa6c1984e5a6f09f7ae503999ef7e22e1fdfcf67aea2aca1a56af608405300ad78366b049e9b282c42c07b1a6635494a2d1d38bc5023e30747393c803ac7df3

test:
  secret_key_base: 416e8b11897f6ea4fd7c60a5c3cd3688baa606541c9b07521a7378d6b27b30b25aea9dd5b88c8ed12c984c7599f10620309a04fbd8328264b8a7090181772571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
